version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app/backend
    environment:
      - SKIP_DB_CHECK=false
      - MOCK_SUPABASE=false

  # Le service local Supabase a été supprimé pour simplifier la structure
  # En cas de besoin, utiliser la CLI Supabase directement (supabase start)
