version: '3.8'

services:
  # Service FastAPI (utilise le Dockerfile existant)
  api:
    build:
      context: .
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
